//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.MdmServiceTest {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esv.dlt.go.th")]
    public partial class businessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string faultNameField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultName {
            get {
                return this.faultNameField;
            }
            set {
                this.faultNameField = value;
                this.RaisePropertyChanged("faultName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esv.dlt.go.th")]
    public partial class authenUserResultBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool authenUserResultField;
        
        private bool authenUserResultFieldSpecified;
        
        private string authenUserTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool authenUserResult {
            get {
                return this.authenUserResultField;
            }
            set {
                this.authenUserResultField = value;
                this.RaisePropertyChanged("authenUserResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool authenUserResultSpecified {
            get {
                return this.authenUserResultFieldSpecified;
            }
            set {
                this.authenUserResultFieldSpecified = value;
                this.RaisePropertyChanged("authenUserResultSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string authenUserToken {
            get {
                return this.authenUserTokenField;
            }
            set {
                this.authenUserTokenField = value;
                this.RaisePropertyChanged("authenUserToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="authenUserResponse", Namespace="http://ws.esv.dlt.go.th")]
    public partial class authenUserResponse1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private authenUserResultBean returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public authenUserResultBean @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esv.dlt.go.th")]
    public partial class AuthenUserOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private authenUserResponse1 authenUserResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.esv.dlt.go.th", Order=0)]
        public authenUserResponse1 authenUserResponse {
            get {
                return this.authenUserResponseField;
            }
            set {
                this.authenUserResponseField = value;
                this.RaisePropertyChanged("authenUserResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esv.dlt.go.th")]
    public partial class AuthenticationInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIdField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esv.dlt.go.th")]
    public partial class authenUserBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ipAddressField;
        
        private string passwordField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("ipAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esv.dlt.go.th")]
    public partial class AuthenUserInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private authenUserBean authenUserBeanInputField;
        
        private AuthenticationInput authenticationInputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public authenUserBean authenUserBeanInput {
            get {
                return this.authenUserBeanInputField;
            }
            set {
                this.authenUserBeanInputField = value;
                this.RaisePropertyChanged("authenUserBeanInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public AuthenticationInput authenticationInput {
            get {
                return this.authenticationInputField;
            }
            set {
                this.authenticationInputField = value;
                this.RaisePropertyChanged("authenticationInput");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esv.dlt.go.th")]
    public partial class systemException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string exceptionNameField;
        
        private string faultNameField;
        
        private string messageField;
        
        private string stacktraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string exceptionName {
            get {
                return this.exceptionNameField;
            }
            set {
                this.exceptionNameField = value;
                this.RaisePropertyChanged("exceptionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string faultName {
            get {
                return this.faultNameField;
            }
            set {
                this.faultNameField = value;
                this.RaisePropertyChanged("faultName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string stacktrace {
            get {
                return this.stacktraceField;
            }
            set {
                this.stacktraceField = value;
                this.RaisePropertyChanged("stacktrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esv.dlt.go.th", ConfigurationName="MdmServiceTest.MdmUserService")]
    public interface MdmUserService {
        
        // CODEGEN: Generating message contract since the operation authenUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://esv.dlt.go.th/MdmUserService/authenUser", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DLSM.MdmServiceTest.businessException), Action="http://esv.dlt.go.th/MdmUserService/authenUser", Name="BusinessFault", Namespace="http://ws.esv.dlt.go.th")]
        [System.ServiceModel.FaultContractAttribute(typeof(DLSM.MdmServiceTest.systemException), Action="http://esv.dlt.go.th/MdmUserService/authenUser", Name="SystemFault", Namespace="http://ws.esv.dlt.go.th")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DLSM.MdmServiceTest.authenUserResponse2 authenUser(DLSM.MdmServiceTest.authenUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esv.dlt.go.th/MdmUserService/authenUser", ReplyAction="*")]
        System.Threading.Tasks.Task<DLSM.MdmServiceTest.authenUserResponse2> authenUserAsync(DLSM.MdmServiceTest.authenUserRequest request);
        
        // CODEGEN: Generating message contract since the operation getUserInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://esv.dlt.go.th/MdmUserService/getUserInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DLSM.MdmServiceTest.businessException), Action="http://esv.dlt.go.th/MdmUserService/getUserInfo", Name="BusinessFault", Namespace="http://ws.esv.dlt.go.th")]
        [System.ServiceModel.FaultContractAttribute(typeof(DLSM.MdmServiceTest.systemException), Action="http://esv.dlt.go.th/MdmUserService/getUserInfo", Name="SystemFault", Namespace="http://ws.esv.dlt.go.th")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DLSM.MdmServiceTest.getUserInfoResponse2 getUserInfo(DLSM.MdmServiceTest.getUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esv.dlt.go.th/MdmUserService/getUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<DLSM.MdmServiceTest.getUserInfoResponse2> getUserInfoAsync(DLSM.MdmServiceTest.getUserInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esv.dlt.go.th")]
    public partial class authenUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthenUserInput authenUserInputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AuthenUserInput AuthenUserInput {
            get {
                return this.authenUserInputField;
            }
            set {
                this.authenUserInputField = value;
                this.RaisePropertyChanged("AuthenUserInput");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esv.dlt.go.th")]
    public partial class authenUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthenUserOutput authenUserOutputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public AuthenUserOutput AuthenUserOutput {
            get {
                return this.authenUserOutputField;
            }
            set {
                this.authenUserOutputField = value;
                this.RaisePropertyChanged("AuthenUserOutput");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://esv.dlt.go.th", Order=0)]
        public DLSM.MdmServiceTest.authenUser authenUser;
        
        public authenUserRequest() {
        }
        
        public authenUserRequest(DLSM.MdmServiceTest.authenUser authenUser) {
            this.authenUser = authenUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenUserResponse2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://esv.dlt.go.th", Order=0)]
        public DLSM.MdmServiceTest.authenUserResponse authenUserResponse;
        
        public authenUserResponse2() {
        }
        
        public authenUserResponse2(DLSM.MdmServiceTest.authenUserResponse authenUserResponse) {
            this.authenUserResponse = authenUserResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esv.dlt.go.th")]
    public partial class getUserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetUserInfoInput getUserInfoInputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public GetUserInfoInput GetUserInfoInput {
            get {
                return this.getUserInfoInputField;
            }
            set {
                this.getUserInfoInputField = value;
                this.RaisePropertyChanged("GetUserInfoInput");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esv.dlt.go.th")]
    public partial class GetUserInfoInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getUserInfoBean getUserInfoBeanInputField;
        
        private AuthenticationInput authenticationInputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getUserInfoBean getUserInfoBeanInput {
            get {
                return this.getUserInfoBeanInputField;
            }
            set {
                this.getUserInfoBeanInputField = value;
                this.RaisePropertyChanged("getUserInfoBeanInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public AuthenticationInput authenticationInput {
            get {
                return this.authenticationInputField;
            }
            set {
                this.authenticationInputField = value;
                this.RaisePropertyChanged("authenticationInput");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esv.dlt.go.th")]
    public partial class getUserInfoBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authenUserTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authenUserToken {
            get {
                return this.authenUserTokenField;
            }
            set {
                this.authenUserTokenField = value;
                this.RaisePropertyChanged("authenUserToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esv.dlt.go.th")]
    public partial class getUserInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetUserInfoOutput getUserInfoOutputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public GetUserInfoOutput GetUserInfoOutput {
            get {
                return this.getUserInfoOutputField;
            }
            set {
                this.getUserInfoOutputField = value;
                this.RaisePropertyChanged("GetUserInfoOutput");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esv.dlt.go.th")]
    public partial class GetUserInfoOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getUserInfoResponse1 getUserInfoResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.esv.dlt.go.th", Order=0)]
        public getUserInfoResponse1 getUserInfoResponse {
            get {
                return this.getUserInfoResponseField;
            }
            set {
                this.getUserInfoResponseField = value;
                this.RaisePropertyChanged("getUserInfoResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="getUserInfoResponse", Namespace="http://ws.esv.dlt.go.th")]
    public partial class getUserInfoResponse1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getUserInfoResultBean returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getUserInfoResultBean @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esv.dlt.go.th")]
    public partial class getUserInfoResultBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string offLocCodeField;
        
        private string offLocDescField;
        
        private string orgFullNameDesField;
        
        private string positionDescField;
        
        private string surnameField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string offLocCode {
            get {
                return this.offLocCodeField;
            }
            set {
                this.offLocCodeField = value;
                this.RaisePropertyChanged("offLocCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string offLocDesc {
            get {
                return this.offLocDescField;
            }
            set {
                this.offLocDescField = value;
                this.RaisePropertyChanged("offLocDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string orgFullNameDes {
            get {
                return this.orgFullNameDesField;
            }
            set {
                this.orgFullNameDesField = value;
                this.RaisePropertyChanged("orgFullNameDes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string positionDesc {
            get {
                return this.positionDescField;
            }
            set {
                this.positionDescField = value;
                this.RaisePropertyChanged("positionDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://esv.dlt.go.th", Order=0)]
        public DLSM.MdmServiceTest.getUserInfo getUserInfo;
        
        public getUserInfoRequest() {
        }
        
        public getUserInfoRequest(DLSM.MdmServiceTest.getUserInfo getUserInfo) {
            this.getUserInfo = getUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoResponse2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://esv.dlt.go.th", Order=0)]
        public DLSM.MdmServiceTest.getUserInfoResponse getUserInfoResponse;
        
        public getUserInfoResponse2() {
        }
        
        public getUserInfoResponse2(DLSM.MdmServiceTest.getUserInfoResponse getUserInfoResponse) {
            this.getUserInfoResponse = getUserInfoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MdmUserServiceChannel : DLSM.MdmServiceTest.MdmUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MdmUserServiceClient : System.ServiceModel.ClientBase<DLSM.MdmServiceTest.MdmUserService>, DLSM.MdmServiceTest.MdmUserService {
        
        public MdmUserServiceClient() {
        }
        
        public MdmUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MdmUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MdmUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MdmUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DLSM.MdmServiceTest.authenUserResponse2 DLSM.MdmServiceTest.MdmUserService.authenUser(DLSM.MdmServiceTest.authenUserRequest request) {
            return base.Channel.authenUser(request);
        }
        
        public DLSM.MdmServiceTest.authenUserResponse authenUser(DLSM.MdmServiceTest.authenUser authenUser1) {
            DLSM.MdmServiceTest.authenUserRequest inValue = new DLSM.MdmServiceTest.authenUserRequest();
            inValue.authenUser = authenUser1;
            DLSM.MdmServiceTest.authenUserResponse2 retVal = ((DLSM.MdmServiceTest.MdmUserService)(this)).authenUser(inValue);
            return retVal.authenUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DLSM.MdmServiceTest.authenUserResponse2> DLSM.MdmServiceTest.MdmUserService.authenUserAsync(DLSM.MdmServiceTest.authenUserRequest request) {
            return base.Channel.authenUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<DLSM.MdmServiceTest.authenUserResponse2> authenUserAsync(DLSM.MdmServiceTest.authenUser authenUser) {
            DLSM.MdmServiceTest.authenUserRequest inValue = new DLSM.MdmServiceTest.authenUserRequest();
            inValue.authenUser = authenUser;
            return ((DLSM.MdmServiceTest.MdmUserService)(this)).authenUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DLSM.MdmServiceTest.getUserInfoResponse2 DLSM.MdmServiceTest.MdmUserService.getUserInfo(DLSM.MdmServiceTest.getUserInfoRequest request) {
            return base.Channel.getUserInfo(request);
        }
        
        public DLSM.MdmServiceTest.getUserInfoResponse getUserInfo(DLSM.MdmServiceTest.getUserInfo getUserInfo1) {
            DLSM.MdmServiceTest.getUserInfoRequest inValue = new DLSM.MdmServiceTest.getUserInfoRequest();
            inValue.getUserInfo = getUserInfo1;
            DLSM.MdmServiceTest.getUserInfoResponse2 retVal = ((DLSM.MdmServiceTest.MdmUserService)(this)).getUserInfo(inValue);
            return retVal.getUserInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DLSM.MdmServiceTest.getUserInfoResponse2> DLSM.MdmServiceTest.MdmUserService.getUserInfoAsync(DLSM.MdmServiceTest.getUserInfoRequest request) {
            return base.Channel.getUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DLSM.MdmServiceTest.getUserInfoResponse2> getUserInfoAsync(DLSM.MdmServiceTest.getUserInfo getUserInfo) {
            DLSM.MdmServiceTest.getUserInfoRequest inValue = new DLSM.MdmServiceTest.getUserInfoRequest();
            inValue.getUserInfo = getUserInfo;
            return ((DLSM.MdmServiceTest.MdmUserService)(this)).getUserInfoAsync(inValue);
        }
    }
}
