//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.Issues = new HashSet<Issue>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="กรุณากรอกหัวเรื่อง")]
        public string Subject { get; set; }
        public string Symptom { get; set; }
        public string Cause { get; set; }
        public string Solving { get; set; }
        public Nullable<int> CreateBy { get; set; }
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy}")]
        public Nullable<System.DateTime> CreateDate { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกกลุ่มปัญหา")]
        public Nullable<int> TgID { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public string CreateName { get; set; }
        public string TgName { get; set; }
        public string Name { get; set; }

        public List<OldList> OldList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual TopicGroup TopicGroup { get; set; }
    }
    public class OldList
    {
        public int OldID { get; set; }
        public string OldSubject { get; set; }
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy}")]
        public Nullable<System.DateTime> OldCreateDate { get; set; }
    }
}
