//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TransferStaff
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกเจ้าหน้าที่")]
        public Nullable<int> StID { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกจากคลังวัสดุ")]
        public Nullable<int> FromWhID { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกไปคลังวัสดุ")]
        public Nullable<int> ToWhID { get; set; }
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy}")]
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกบทบาทในสำนักงานขนส่ง")]
        public string IsManager { get; set; }
    
        public string StName { get; set; }
        public string FromWhName { get; set; }
        public string ToWhName { get; set; }

        public virtual Staff Staff { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
