//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse()
        {
            this.Issues = new HashSet<Issue>();
            this.Stocks = new HashSet<Stock>();
            this.TransferStaffs = new HashSet<TransferStaff>();
            this.TransferStaffs1 = new HashSet<TransferStaff>();
            this.WarehouseMinimums = new HashSet<WarehouseMinimum>();
            this.StaffWarehouses = new HashSet<StaffWarehouse>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "กรุณากรอกรหัสสำนักงานขนส่ง")]
        public string Code { get; set; }
        [Required(ErrorMessage = "กรุณากรอกชื่อสำนักงานขนส่ง")]
        public string Name { get; set; }        
        public string TelNo { get; set; }        
        public string Email { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกสถานะของสำนักงานขนส่ง")]
        public string IsMain { get; set; }
        public string NameEN { get; set; }
        public string LocationName { get; set; }
        public string BackgroundPicture { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> ImageUpdate { get; set; }
        public Nullable<int> PvID { get; set; }
		
        public System.Web.HttpPostedFileBase BG64 { get; set; }
	
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> Issues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferStaff> TransferStaffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferStaff> TransferStaffs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseMinimum> WarehouseMinimums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffWarehouse> StaffWarehouses { get; set; }
    }
}
