//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WorkStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkStation()
        {
            this.WorkSationDetails = new HashSet<WorkSationDetail>();
            this.WorkSationStaffs = new HashSet<WorkSationStaff>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="กรุณากรอกชื่อ WorkStation")]
        public string Name { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกคลังวัสดุ")]
        public int WhID { get; set; }
        public string WhName { get; set; }
        public string Remark { get; set; }
        public string PrinterName { get; set; }
        public List<WorkStationStaffList> WorkStationStaffList { get; set; }
        public List<WorkStationDetailList> WorkStationDetailList { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSationDetail> WorkSationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSationStaff> WorkSationStaffs { get; set; }
    }
    public class WorkStationDetailList
    {
        public Nullable<int> WsID { get; set; }
        public Nullable<int> PdID { get; set; }
        public string SerialNO { get; set; }
        public string PdName { get; set; }
        public string IP { get; set; }
        public string Name { get; set; }
    }

    public class WorkStationStaffList
    {
        public Nullable<int> WsID { get; set; }
        public Nullable<int> StID { get; set; }
        public string StName { get; set; }
    }
}
