//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DLSMEntities : DbContext
    {
        public DLSMEntities()
            : base("name=DLSMEntities")
        {
        }
    
      //  protected override void OnModelCreating(DbModelBuilder modelBuilder)
      //  {
    	 //modelBuilder.Entity<Document>().HasRequired(c => c.SpID)
      //               .WillCascadeOnCreate(false); 
    		//		 .WillCascadeOnUpdate(false); 
    		//		 .WillCascadeOnDelete(false); 
      //      throw new UnintentionalCodeFirstException();
      //  }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Commend> Commends { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SerialImagePart> SerialImageParts { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockSerial> StockSerials { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TopicGroup> TopicGroups { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<WorkHistory> WorkHistories { get; set; }
        public virtual DbSet<TransferStaff> TransferStaffs { get; set; }
        public virtual DbSet<WorkSationDetail> WorkSationDetails { get; set; }
        public virtual DbSet<WorkSationStaff> WorkSationStaffs { get; set; }
        public virtual DbSet<WorkStation> WorkStations { get; set; }
        public virtual DbSet<WarehouseMinimum> WarehouseMinimums { get; set; }
        public virtual DbSet<SerialOut> SerialOuts { get; set; }
        public virtual DbSet<StaffWarehouse> StaffWarehouses { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Configure> Configures { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<GetUserInfo> GetUserInfoes { get; set; }
    
        public virtual ObjectResult<sp_ApiCheckCardSerial_Result> sp_ApiCheckCardSerial(Nullable<int> whid, string serialNo, Nullable<int> staffid)
        {
            var whidParameter = whid.HasValue ?
                new ObjectParameter("whid", whid) :
                new ObjectParameter("whid", typeof(int));
    
            var serialNoParameter = serialNo != null ?
                new ObjectParameter("serialNo", serialNo) :
                new ObjectParameter("serialNo", typeof(string));
    
            var staffidParameter = staffid.HasValue ?
                new ObjectParameter("staffid", staffid) :
                new ObjectParameter("staffid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiCheckCardSerial_Result>("sp_ApiCheckCardSerial", whidParameter, serialNoParameter, staffidParameter);
        }
    
        public virtual int sp_createAdjustDoc(Nullable<int> docID, string docType, string remark, Nullable<int> whID, Nullable<int> pdID, Nullable<int> qty, string ttype)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            var docTypeParameter = docType != null ?
                new ObjectParameter("docType", docType) :
                new ObjectParameter("docType", typeof(string));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var whIDParameter = whID.HasValue ?
                new ObjectParameter("whID", whID) :
                new ObjectParameter("whID", typeof(int));
    
            var pdIDParameter = pdID.HasValue ?
                new ObjectParameter("pdID", pdID) :
                new ObjectParameter("pdID", typeof(int));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("qty", qty) :
                new ObjectParameter("qty", typeof(int));
    
            var ttypeParameter = ttype != null ?
                new ObjectParameter("ttype", ttype) :
                new ObjectParameter("ttype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_createAdjustDoc", docIDParameter, docTypeParameter, remarkParameter, whIDParameter, pdIDParameter, qtyParameter, ttypeParameter);
        }
    
        public virtual ObjectResult<sp_CreateCardUsageDoc_Result> sp_CreateCardUsageDoc(Nullable<int> whID, Nullable<int> stID, string cardNo)
        {
            var whIDParameter = whID.HasValue ?
                new ObjectParameter("whID", whID) :
                new ObjectParameter("whID", typeof(int));
    
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("stID", stID) :
                new ObjectParameter("stID", typeof(int));
    
            var cardNoParameter = cardNo != null ?
                new ObjectParameter("CardNo", cardNo) :
                new ObjectParameter("CardNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CreateCardUsageDoc_Result>("sp_CreateCardUsageDoc", whIDParameter, stIDParameter, cardNoParameter);
        }
    
        public virtual int sp_ProcessDetail(Nullable<int> docID, Nullable<int> whID, Nullable<int> whID2, string docType, string type)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            var whIDParameter = whID.HasValue ?
                new ObjectParameter("whID", whID) :
                new ObjectParameter("whID", typeof(int));
    
            var whID2Parameter = whID2.HasValue ?
                new ObjectParameter("whID2", whID2) :
                new ObjectParameter("whID2", typeof(int));
    
            var docTypeParameter = docType != null ?
                new ObjectParameter("docType", docType) :
                new ObjectParameter("docType", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcessDetail", docIDParameter, whIDParameter, whID2Parameter, docTypeParameter, typeParameter);
        }
    
        public virtual int sp_ProcessDetailCopy(Nullable<int> docID, string type)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcessDetailCopy", docIDParameter, typeParameter);
        }
    
        public virtual int sp_ProcessSerialIN(Nullable<int> docID)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcessSerialIN", docIDParameter);
        }
    
        public virtual int sp_ProcessSerialOut(Nullable<int> docID)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcessSerialOut", docIDParameter);
        }
    
        public virtual ObjectResult<sp_RptBalance_Result> sp_RptBalance(Nullable<int> whid, Nullable<int> stidpermit)
        {
            var whidParameter = whid.HasValue ?
                new ObjectParameter("whid", whid) :
                new ObjectParameter("whid", typeof(int));
    
            var stidpermitParameter = stidpermit.HasValue ?
                new ObjectParameter("stidpermit", stidpermit) :
                new ObjectParameter("stidpermit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptBalance_Result>("sp_RptBalance", whidParameter, stidpermitParameter);
        }
    
        public virtual int sp_RptMovement(string date1, string date2, Nullable<int> whid, Nullable<int> pdid, Nullable<int> stidpermit)
        {
            var date1Parameter = date1 != null ?
                new ObjectParameter("date1", date1) :
                new ObjectParameter("date1", typeof(string));
    
            var date2Parameter = date2 != null ?
                new ObjectParameter("date2", date2) :
                new ObjectParameter("date2", typeof(string));
    
            var whidParameter = whid.HasValue ?
                new ObjectParameter("whid", whid) :
                new ObjectParameter("whid", typeof(int));
    
            var pdidParameter = pdid.HasValue ?
                new ObjectParameter("pdid", pdid) :
                new ObjectParameter("pdid", typeof(int));
    
            var stidpermitParameter = stidpermit.HasValue ?
                new ObjectParameter("stidpermit", stidpermit) :
                new ObjectParameter("stidpermit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RptMovement", date1Parameter, date2Parameter, whidParameter, pdidParameter, stidpermitParameter);
        }
    
        public virtual int sp_RptNotEnough(Nullable<int> whid, Nullable<int> stid)
        {
            var whidParameter = whid.HasValue ?
                new ObjectParameter("whid", whid) :
                new ObjectParameter("whid", typeof(int));
    
            var stidParameter = stid.HasValue ?
                new ObjectParameter("stid", stid) :
                new ObjectParameter("stid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RptNotEnough", whidParameter, stidParameter);
        }
    
        public virtual int sp_RptReceive(string date1, string date2, Nullable<int> whid, Nullable<int> pdid, Nullable<int> stid, Nullable<int> stidpermit)
        {
            var date1Parameter = date1 != null ?
                new ObjectParameter("date1", date1) :
                new ObjectParameter("date1", typeof(string));
    
            var date2Parameter = date2 != null ?
                new ObjectParameter("date2", date2) :
                new ObjectParameter("date2", typeof(string));
    
            var whidParameter = whid.HasValue ?
                new ObjectParameter("whid", whid) :
                new ObjectParameter("whid", typeof(int));
    
            var pdidParameter = pdid.HasValue ?
                new ObjectParameter("pdid", pdid) :
                new ObjectParameter("pdid", typeof(int));
    
            var stidParameter = stid.HasValue ?
                new ObjectParameter("stid", stid) :
                new ObjectParameter("stid", typeof(int));
    
            var stidpermitParameter = stidpermit.HasValue ?
                new ObjectParameter("stidpermit", stidpermit) :
                new ObjectParameter("stidpermit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RptReceive", date1Parameter, date2Parameter, whidParameter, pdidParameter, stidParameter, stidpermitParameter);
        }
    
        public virtual int sp_RptRequisition(string date1, string date2, Nullable<int> whid, Nullable<int> pdid, Nullable<int> stid, Nullable<int> stidpermit)
        {
            var date1Parameter = date1 != null ?
                new ObjectParameter("date1", date1) :
                new ObjectParameter("date1", typeof(string));
    
            var date2Parameter = date2 != null ?
                new ObjectParameter("date2", date2) :
                new ObjectParameter("date2", typeof(string));
    
            var whidParameter = whid.HasValue ?
                new ObjectParameter("whid", whid) :
                new ObjectParameter("whid", typeof(int));
    
            var pdidParameter = pdid.HasValue ?
                new ObjectParameter("pdid", pdid) :
                new ObjectParameter("pdid", typeof(int));
    
            var stidParameter = stid.HasValue ?
                new ObjectParameter("stid", stid) :
                new ObjectParameter("stid", typeof(int));
    
            var stidpermitParameter = stidpermit.HasValue ?
                new ObjectParameter("stidpermit", stidpermit) :
                new ObjectParameter("stidpermit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RptRequisition", date1Parameter, date2Parameter, whidParameter, pdidParameter, stidParameter, stidpermitParameter);
        }
    
        public virtual ObjectResult<sp_RptTransfer_Result> sp_RptTransfer(Nullable<int> whid, Nullable<int> stidpermit)
        {
            var whidParameter = whid.HasValue ?
                new ObjectParameter("whid", whid) :
                new ObjectParameter("whid", typeof(int));
    
            var stidpermitParameter = stidpermit.HasValue ?
                new ObjectParameter("stidpermit", stidpermit) :
                new ObjectParameter("stidpermit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptTransfer_Result>("sp_RptTransfer", whidParameter, stidpermitParameter);
        }
    
        public virtual ObjectResult<sp_ProcessDocument_Result> sp_ProcessDocument(Nullable<int> docID, Nullable<int> stID)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("stID", stID) :
                new ObjectParameter("stID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ProcessDocument_Result>("sp_ProcessDocument", docIDParameter, stIDParameter);
        }
    
        public virtual ObjectResult<sp_ApiUpdatePrintStatus_Result> sp_ApiUpdatePrintStatus(string serialNo, string printStatus, string printerStatus)
        {
            var serialNoParameter = serialNo != null ?
                new ObjectParameter("SerialNo", serialNo) :
                new ObjectParameter("SerialNo", typeof(string));
    
            var printStatusParameter = printStatus != null ?
                new ObjectParameter("PrintStatus", printStatus) :
                new ObjectParameter("PrintStatus", typeof(string));
    
            var printerStatusParameter = printerStatus != null ?
                new ObjectParameter("PrinterStatus", printerStatus) :
                new ObjectParameter("PrinterStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiUpdatePrintStatus_Result>("sp_ApiUpdatePrintStatus", serialNoParameter, printStatusParameter, printerStatusParameter);
        }
    
        public virtual ObjectResult<sp_ApiUpdateCardInfo_Result> sp_ApiUpdateCardInfo(Nullable<int> staffId, Nullable<int> wH_ID, string cardEIN, string cardStatus, string qrCode, string startPrintDttmStr, string finishPrintDttmStr, string cardCount, string saveMDMStatus, string saveMDMDesc, string prnErrDesc)
        {
            var staffIdParameter = staffId.HasValue ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(int));
    
            var wH_IDParameter = wH_ID.HasValue ?
                new ObjectParameter("WH_ID", wH_ID) :
                new ObjectParameter("WH_ID", typeof(int));
    
            var cardEINParameter = cardEIN != null ?
                new ObjectParameter("CardEIN", cardEIN) :
                new ObjectParameter("CardEIN", typeof(string));
    
            var cardStatusParameter = cardStatus != null ?
                new ObjectParameter("cardStatus", cardStatus) :
                new ObjectParameter("cardStatus", typeof(string));
    
            var qrCodeParameter = qrCode != null ?
                new ObjectParameter("qrCode", qrCode) :
                new ObjectParameter("qrCode", typeof(string));
    
            var startPrintDttmStrParameter = startPrintDttmStr != null ?
                new ObjectParameter("startPrintDttmStr", startPrintDttmStr) :
                new ObjectParameter("startPrintDttmStr", typeof(string));
    
            var finishPrintDttmStrParameter = finishPrintDttmStr != null ?
                new ObjectParameter("finishPrintDttmStr", finishPrintDttmStr) :
                new ObjectParameter("finishPrintDttmStr", typeof(string));
    
            var cardCountParameter = cardCount != null ?
                new ObjectParameter("cardCount", cardCount) :
                new ObjectParameter("cardCount", typeof(string));
    
            var saveMDMStatusParameter = saveMDMStatus != null ?
                new ObjectParameter("saveMDMStatus", saveMDMStatus) :
                new ObjectParameter("saveMDMStatus", typeof(string));
    
            var saveMDMDescParameter = saveMDMDesc != null ?
                new ObjectParameter("saveMDMDesc", saveMDMDesc) :
                new ObjectParameter("saveMDMDesc", typeof(string));
    
            var prnErrDescParameter = prnErrDesc != null ?
                new ObjectParameter("prnErrDesc", prnErrDesc) :
                new ObjectParameter("prnErrDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiUpdateCardInfo_Result>("sp_ApiUpdateCardInfo", staffIdParameter, wH_IDParameter, cardEINParameter, cardStatusParameter, qrCodeParameter, startPrintDttmStrParameter, finishPrintDttmStrParameter, cardCountParameter, saveMDMStatusParameter, saveMDMDescParameter, prnErrDescParameter);
        }
    
        public virtual ObjectResult<sp_CheckAvailable_Result> sp_CheckAvailable(Nullable<int> docID)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CheckAvailable_Result>("sp_CheckAvailable", docIDParameter);
        }
    
        public virtual ObjectResult<sp_CheckSerialIN_Result> sp_CheckSerialIN(Nullable<int> docID)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CheckSerialIN_Result>("sp_CheckSerialIN", docIDParameter);
        }
    
        public virtual ObjectResult<sp_CheckSerialOut_Result> sp_CheckSerialOut(Nullable<int> docID)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CheckSerialOut_Result>("sp_CheckSerialOut", docIDParameter);
        }
    
        public virtual ObjectResult<sp_ApiLogin_Result> sp_ApiLogin(string username, string password, string workStationName)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var workStationNameParameter = workStationName != null ?
                new ObjectParameter("workStationName", workStationName) :
                new ObjectParameter("workStationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiLogin_Result>("sp_ApiLogin", usernameParameter, passwordParameter, workStationNameParameter);
        }
    
        public virtual ObjectResult<sp_ApiProvImage_Result> sp_ApiProvImage(Nullable<System.DateTime> req_date)
        {
            var req_dateParameter = req_date.HasValue ?
                new ObjectParameter("req_date", req_date) :
                new ObjectParameter("req_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiProvImage_Result>("sp_ApiProvImage", req_dateParameter);
        }
    
        public virtual ObjectResult<sp_ApiUpdatePicture_Result> sp_ApiUpdatePicture(string cardEIN, string wH_ID, string person_image)
        {
            var cardEINParameter = cardEIN != null ?
                new ObjectParameter("cardEIN", cardEIN) :
                new ObjectParameter("cardEIN", typeof(string));
    
            var wH_IDParameter = wH_ID != null ?
                new ObjectParameter("WH_ID", wH_ID) :
                new ObjectParameter("WH_ID", typeof(string));
    
            var person_imageParameter = person_image != null ?
                new ObjectParameter("person_image", person_image) :
                new ObjectParameter("person_image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiUpdatePicture_Result>("sp_ApiUpdatePicture", cardEINParameter, wH_IDParameter, person_imageParameter);
        }
    
        public virtual ObjectResult<sp_ApiPersonImage_Result> sp_ApiPersonImage(string citizenId)
        {
            var citizenIdParameter = citizenId != null ?
                new ObjectParameter("citizenId", citizenId) :
                new ObjectParameter("citizenId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiPersonImage_Result>("sp_ApiPersonImage", citizenIdParameter);
        }
    
        public virtual ObjectResult<sp_ApiSaveCard_Result> sp_ApiSaveCard(string addrNo, string ampDesc, string ampDescEng, string birthDateStr, string birthFlag, string distDesc, string distDescEng, string docNo, string docType, string reqMasRef, string expDateStr, string fname, string fnameEng, string issDateStr, string issOffLocCode, string lane, string lname, string lnameEng, string locFullDesc, string message, string natDesc, string offLocDesc, string offLocEngDesc, string offRegDesc, string offRegEngDesc, string pcNo, string pltCode, string pltDesc, string pltEngDesc, string pltNo, string pltPrnDesc, string prevExpDateStr, string prevIssDateStr, string prevOffLocDesc, string prevOffRegDesc, string prevOffRegEngDesc, string prevPltDesc, string prevPltNo, string prvCode, string prvDesc, string prvDescEng, string rcpNo, string reqDateStr, string reqNo, string reqTrDesc, string sex, string soi, string street, string titleAbrev, string titleDesc, string titleEngAbrev, string villageNo, string zipCode, string alienFlag, string ccFlag, string dCICode, string conditionDesc, string organDonateFlag, string tRSFlag, string firstIssueDateStr, string pltDescShort, string pltNo1, string pltNo2, string prevPltDescShort, string prevPltNo1, string prevPltNo2, string pltNoEng, string wH_ID, string staffId, string workstationId, string productType, string cardEIN, string qrCode)
        {
            var addrNoParameter = addrNo != null ?
                new ObjectParameter("addrNo", addrNo) :
                new ObjectParameter("addrNo", typeof(string));
    
            var ampDescParameter = ampDesc != null ?
                new ObjectParameter("ampDesc", ampDesc) :
                new ObjectParameter("ampDesc", typeof(string));
    
            var ampDescEngParameter = ampDescEng != null ?
                new ObjectParameter("ampDescEng", ampDescEng) :
                new ObjectParameter("ampDescEng", typeof(string));
    
            var birthDateStrParameter = birthDateStr != null ?
                new ObjectParameter("birthDateStr", birthDateStr) :
                new ObjectParameter("birthDateStr", typeof(string));
    
            var birthFlagParameter = birthFlag != null ?
                new ObjectParameter("birthFlag", birthFlag) :
                new ObjectParameter("birthFlag", typeof(string));
    
            var distDescParameter = distDesc != null ?
                new ObjectParameter("distDesc", distDesc) :
                new ObjectParameter("distDesc", typeof(string));
    
            var distDescEngParameter = distDescEng != null ?
                new ObjectParameter("distDescEng", distDescEng) :
                new ObjectParameter("distDescEng", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("docNo", docNo) :
                new ObjectParameter("docNo", typeof(string));
    
            var docTypeParameter = docType != null ?
                new ObjectParameter("docType", docType) :
                new ObjectParameter("docType", typeof(string));
    
            var reqMasRefParameter = reqMasRef != null ?
                new ObjectParameter("reqMasRef", reqMasRef) :
                new ObjectParameter("reqMasRef", typeof(string));
    
            var expDateStrParameter = expDateStr != null ?
                new ObjectParameter("expDateStr", expDateStr) :
                new ObjectParameter("expDateStr", typeof(string));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var fnameEngParameter = fnameEng != null ?
                new ObjectParameter("fnameEng", fnameEng) :
                new ObjectParameter("fnameEng", typeof(string));
    
            var issDateStrParameter = issDateStr != null ?
                new ObjectParameter("issDateStr", issDateStr) :
                new ObjectParameter("issDateStr", typeof(string));
    
            var issOffLocCodeParameter = issOffLocCode != null ?
                new ObjectParameter("issOffLocCode", issOffLocCode) :
                new ObjectParameter("issOffLocCode", typeof(string));
    
            var laneParameter = lane != null ?
                new ObjectParameter("lane", lane) :
                new ObjectParameter("lane", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var lnameEngParameter = lnameEng != null ?
                new ObjectParameter("lnameEng", lnameEng) :
                new ObjectParameter("lnameEng", typeof(string));
    
            var locFullDescParameter = locFullDesc != null ?
                new ObjectParameter("locFullDesc", locFullDesc) :
                new ObjectParameter("locFullDesc", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            var natDescParameter = natDesc != null ?
                new ObjectParameter("natDesc", natDesc) :
                new ObjectParameter("natDesc", typeof(string));
    
            var offLocDescParameter = offLocDesc != null ?
                new ObjectParameter("offLocDesc", offLocDesc) :
                new ObjectParameter("offLocDesc", typeof(string));
    
            var offLocEngDescParameter = offLocEngDesc != null ?
                new ObjectParameter("offLocEngDesc", offLocEngDesc) :
                new ObjectParameter("offLocEngDesc", typeof(string));
    
            var offRegDescParameter = offRegDesc != null ?
                new ObjectParameter("offRegDesc", offRegDesc) :
                new ObjectParameter("offRegDesc", typeof(string));
    
            var offRegEngDescParameter = offRegEngDesc != null ?
                new ObjectParameter("offRegEngDesc", offRegEngDesc) :
                new ObjectParameter("offRegEngDesc", typeof(string));
    
            var pcNoParameter = pcNo != null ?
                new ObjectParameter("pcNo", pcNo) :
                new ObjectParameter("pcNo", typeof(string));
    
            var pltCodeParameter = pltCode != null ?
                new ObjectParameter("pltCode", pltCode) :
                new ObjectParameter("pltCode", typeof(string));
    
            var pltDescParameter = pltDesc != null ?
                new ObjectParameter("pltDesc", pltDesc) :
                new ObjectParameter("pltDesc", typeof(string));
    
            var pltEngDescParameter = pltEngDesc != null ?
                new ObjectParameter("pltEngDesc", pltEngDesc) :
                new ObjectParameter("pltEngDesc", typeof(string));
    
            var pltNoParameter = pltNo != null ?
                new ObjectParameter("pltNo", pltNo) :
                new ObjectParameter("pltNo", typeof(string));
    
            var pltPrnDescParameter = pltPrnDesc != null ?
                new ObjectParameter("pltPrnDesc", pltPrnDesc) :
                new ObjectParameter("pltPrnDesc", typeof(string));
    
            var prevExpDateStrParameter = prevExpDateStr != null ?
                new ObjectParameter("prevExpDateStr", prevExpDateStr) :
                new ObjectParameter("prevExpDateStr", typeof(string));
    
            var prevIssDateStrParameter = prevIssDateStr != null ?
                new ObjectParameter("prevIssDateStr", prevIssDateStr) :
                new ObjectParameter("prevIssDateStr", typeof(string));
    
            var prevOffLocDescParameter = prevOffLocDesc != null ?
                new ObjectParameter("prevOffLocDesc", prevOffLocDesc) :
                new ObjectParameter("prevOffLocDesc", typeof(string));
    
            var prevOffRegDescParameter = prevOffRegDesc != null ?
                new ObjectParameter("prevOffRegDesc", prevOffRegDesc) :
                new ObjectParameter("prevOffRegDesc", typeof(string));
    
            var prevOffRegEngDescParameter = prevOffRegEngDesc != null ?
                new ObjectParameter("prevOffRegEngDesc", prevOffRegEngDesc) :
                new ObjectParameter("prevOffRegEngDesc", typeof(string));
    
            var prevPltDescParameter = prevPltDesc != null ?
                new ObjectParameter("prevPltDesc", prevPltDesc) :
                new ObjectParameter("prevPltDesc", typeof(string));
    
            var prevPltNoParameter = prevPltNo != null ?
                new ObjectParameter("prevPltNo", prevPltNo) :
                new ObjectParameter("prevPltNo", typeof(string));
    
            var prvCodeParameter = prvCode != null ?
                new ObjectParameter("prvCode", prvCode) :
                new ObjectParameter("prvCode", typeof(string));
    
            var prvDescParameter = prvDesc != null ?
                new ObjectParameter("prvDesc", prvDesc) :
                new ObjectParameter("prvDesc", typeof(string));
    
            var prvDescEngParameter = prvDescEng != null ?
                new ObjectParameter("prvDescEng", prvDescEng) :
                new ObjectParameter("prvDescEng", typeof(string));
    
            var rcpNoParameter = rcpNo != null ?
                new ObjectParameter("rcpNo", rcpNo) :
                new ObjectParameter("rcpNo", typeof(string));
    
            var reqDateStrParameter = reqDateStr != null ?
                new ObjectParameter("reqDateStr", reqDateStr) :
                new ObjectParameter("reqDateStr", typeof(string));
    
            var reqNoParameter = reqNo != null ?
                new ObjectParameter("reqNo", reqNo) :
                new ObjectParameter("reqNo", typeof(string));
    
            var reqTrDescParameter = reqTrDesc != null ?
                new ObjectParameter("reqTrDesc", reqTrDesc) :
                new ObjectParameter("reqTrDesc", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var soiParameter = soi != null ?
                new ObjectParameter("soi", soi) :
                new ObjectParameter("soi", typeof(string));
    
            var streetParameter = street != null ?
                new ObjectParameter("street", street) :
                new ObjectParameter("street", typeof(string));
    
            var titleAbrevParameter = titleAbrev != null ?
                new ObjectParameter("titleAbrev", titleAbrev) :
                new ObjectParameter("titleAbrev", typeof(string));
    
            var titleDescParameter = titleDesc != null ?
                new ObjectParameter("titleDesc", titleDesc) :
                new ObjectParameter("titleDesc", typeof(string));
    
            var titleEngAbrevParameter = titleEngAbrev != null ?
                new ObjectParameter("titleEngAbrev", titleEngAbrev) :
                new ObjectParameter("titleEngAbrev", typeof(string));
    
            var villageNoParameter = villageNo != null ?
                new ObjectParameter("villageNo", villageNo) :
                new ObjectParameter("villageNo", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("zipCode", zipCode) :
                new ObjectParameter("zipCode", typeof(string));
    
            var alienFlagParameter = alienFlag != null ?
                new ObjectParameter("alienFlag", alienFlag) :
                new ObjectParameter("alienFlag", typeof(string));
    
            var ccFlagParameter = ccFlag != null ?
                new ObjectParameter("ccFlag", ccFlag) :
                new ObjectParameter("ccFlag", typeof(string));
    
            var dCICodeParameter = dCICode != null ?
                new ObjectParameter("DCICode", dCICode) :
                new ObjectParameter("DCICode", typeof(string));
    
            var conditionDescParameter = conditionDesc != null ?
                new ObjectParameter("conditionDesc", conditionDesc) :
                new ObjectParameter("conditionDesc", typeof(string));
    
            var organDonateFlagParameter = organDonateFlag != null ?
                new ObjectParameter("organDonateFlag", organDonateFlag) :
                new ObjectParameter("organDonateFlag", typeof(string));
    
            var tRSFlagParameter = tRSFlag != null ?
                new ObjectParameter("TRSFlag", tRSFlag) :
                new ObjectParameter("TRSFlag", typeof(string));
    
            var firstIssueDateStrParameter = firstIssueDateStr != null ?
                new ObjectParameter("firstIssueDateStr", firstIssueDateStr) :
                new ObjectParameter("firstIssueDateStr", typeof(string));
    
            var pltDescShortParameter = pltDescShort != null ?
                new ObjectParameter("pltDescShort", pltDescShort) :
                new ObjectParameter("pltDescShort", typeof(string));
    
            var pltNo1Parameter = pltNo1 != null ?
                new ObjectParameter("pltNo1", pltNo1) :
                new ObjectParameter("pltNo1", typeof(string));
    
            var pltNo2Parameter = pltNo2 != null ?
                new ObjectParameter("pltNo2", pltNo2) :
                new ObjectParameter("pltNo2", typeof(string));
    
            var prevPltDescShortParameter = prevPltDescShort != null ?
                new ObjectParameter("prevPltDescShort", prevPltDescShort) :
                new ObjectParameter("prevPltDescShort", typeof(string));
    
            var prevPltNo1Parameter = prevPltNo1 != null ?
                new ObjectParameter("prevPltNo1", prevPltNo1) :
                new ObjectParameter("prevPltNo1", typeof(string));
    
            var prevPltNo2Parameter = prevPltNo2 != null ?
                new ObjectParameter("prevPltNo2", prevPltNo2) :
                new ObjectParameter("prevPltNo2", typeof(string));
    
            var pltNoEngParameter = pltNoEng != null ?
                new ObjectParameter("pltNoEng", pltNoEng) :
                new ObjectParameter("pltNoEng", typeof(string));
    
            var wH_IDParameter = wH_ID != null ?
                new ObjectParameter("WH_ID", wH_ID) :
                new ObjectParameter("WH_ID", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            var workstationIdParameter = workstationId != null ?
                new ObjectParameter("workstationId", workstationId) :
                new ObjectParameter("workstationId", typeof(string));
    
            var productTypeParameter = productType != null ?
                new ObjectParameter("productType", productType) :
                new ObjectParameter("productType", typeof(string));
    
            var cardEINParameter = cardEIN != null ?
                new ObjectParameter("CardEIN", cardEIN) :
                new ObjectParameter("CardEIN", typeof(string));
    
            var qrCodeParameter = qrCode != null ?
                new ObjectParameter("qrCode", qrCode) :
                new ObjectParameter("qrCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiSaveCard_Result>("sp_ApiSaveCard", addrNoParameter, ampDescParameter, ampDescEngParameter, birthDateStrParameter, birthFlagParameter, distDescParameter, distDescEngParameter, docNoParameter, docTypeParameter, reqMasRefParameter, expDateStrParameter, fnameParameter, fnameEngParameter, issDateStrParameter, issOffLocCodeParameter, laneParameter, lnameParameter, lnameEngParameter, locFullDescParameter, messageParameter, natDescParameter, offLocDescParameter, offLocEngDescParameter, offRegDescParameter, offRegEngDescParameter, pcNoParameter, pltCodeParameter, pltDescParameter, pltEngDescParameter, pltNoParameter, pltPrnDescParameter, prevExpDateStrParameter, prevIssDateStrParameter, prevOffLocDescParameter, prevOffRegDescParameter, prevOffRegEngDescParameter, prevPltDescParameter, prevPltNoParameter, prvCodeParameter, prvDescParameter, prvDescEngParameter, rcpNoParameter, reqDateStrParameter, reqNoParameter, reqTrDescParameter, sexParameter, soiParameter, streetParameter, titleAbrevParameter, titleDescParameter, titleEngAbrevParameter, villageNoParameter, zipCodeParameter, alienFlagParameter, ccFlagParameter, dCICodeParameter, conditionDescParameter, organDonateFlagParameter, tRSFlagParameter, firstIssueDateStrParameter, pltDescShortParameter, pltNo1Parameter, pltNo2Parameter, prevPltDescShortParameter, prevPltNo1Parameter, prevPltNo2Parameter, pltNoEngParameter, wH_IDParameter, staffIdParameter, workstationIdParameter, productTypeParameter, cardEINParameter, qrCodeParameter);
        }
    
        public virtual ObjectResult<sp_ApiCancelCard_Result> sp_ApiCancelCard(string wH_ID, string staffId, string cardEIN)
        {
            var wH_IDParameter = wH_ID != null ?
                new ObjectParameter("WH_ID", wH_ID) :
                new ObjectParameter("WH_ID", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            var cardEINParameter = cardEIN != null ?
                new ObjectParameter("cardEIN", cardEIN) :
                new ObjectParameter("cardEIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiCancelCard_Result>("sp_ApiCancelCard", wH_IDParameter, staffIdParameter, cardEINParameter);
        }
    
        public virtual ObjectResult<sp_ApiGetCardInfo_Result> sp_ApiGetCardInfo(string wH_ID, string staffId, string cardEIN)
        {
            var wH_IDParameter = wH_ID != null ?
                new ObjectParameter("WH_ID", wH_ID) :
                new ObjectParameter("WH_ID", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            var cardEINParameter = cardEIN != null ?
                new ObjectParameter("cardEIN", cardEIN) :
                new ObjectParameter("cardEIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiGetCardInfo_Result>("sp_ApiGetCardInfo", wH_IDParameter, staffIdParameter, cardEINParameter);
        }
    
        public virtual ObjectResult<sp_ApiGetListTrans_Result> sp_ApiGetListTrans(string wH_ID, string staffId, string startDateTime, string endDateTime, string productType)
        {
            var wH_IDParameter = wH_ID != null ?
                new ObjectParameter("WH_ID", wH_ID) :
                new ObjectParameter("WH_ID", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            var startDateTimeParameter = startDateTime != null ?
                new ObjectParameter("startDateTime", startDateTime) :
                new ObjectParameter("startDateTime", typeof(string));
    
            var endDateTimeParameter = endDateTime != null ?
                new ObjectParameter("endDateTime", endDateTime) :
                new ObjectParameter("endDateTime", typeof(string));
    
            var productTypeParameter = productType != null ?
                new ObjectParameter("productType", productType) :
                new ObjectParameter("productType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiGetListTrans_Result>("sp_ApiGetListTrans", wH_IDParameter, staffIdParameter, startDateTimeParameter, endDateTimeParameter, productTypeParameter);
        }
    
        public virtual ObjectResult<sp_ApiPrintDailyRept_Result> sp_ApiPrintDailyRept(string wH_ID, string staffId, string rept_type, string rept_date)
        {
            var wH_IDParameter = wH_ID != null ?
                new ObjectParameter("WH_ID", wH_ID) :
                new ObjectParameter("WH_ID", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            var rept_typeParameter = rept_type != null ?
                new ObjectParameter("rept_type", rept_type) :
                new ObjectParameter("rept_type", typeof(string));
    
            var rept_dateParameter = rept_date != null ?
                new ObjectParameter("rept_date", rept_date) :
                new ObjectParameter("rept_date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiPrintDailyRept_Result>("sp_ApiPrintDailyRept", wH_IDParameter, staffIdParameter, rept_typeParameter, rept_dateParameter);
        }
    
        public virtual ObjectResult<sp_CreateBorrow_Result> sp_CreateBorrow(Nullable<int> docid, string docno, string trntype, Nullable<int> createby)
        {
            var docidParameter = docid.HasValue ?
                new ObjectParameter("docid", docid) :
                new ObjectParameter("docid", typeof(int));
    
            var docnoParameter = docno != null ?
                new ObjectParameter("docno", docno) :
                new ObjectParameter("docno", typeof(string));
    
            var trntypeParameter = trntype != null ?
                new ObjectParameter("trntype", trntype) :
                new ObjectParameter("trntype", typeof(string));
    
            var createbyParameter = createby.HasValue ?
                new ObjectParameter("createby", createby) :
                new ObjectParameter("createby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CreateBorrow_Result>("sp_CreateBorrow", docidParameter, docnoParameter, trntypeParameter, createbyParameter);
        }
    
        public virtual ObjectResult<sp_ApiSaveMagInfo_Result> sp_ApiSaveMagInfo(string wH_ID, string staffId, string trans_datetime, string track_01, string track_02, string track_03, string resultCode, string resultMsg)
        {
            var wH_IDParameter = wH_ID != null ?
                new ObjectParameter("WH_ID", wH_ID) :
                new ObjectParameter("WH_ID", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            var trans_datetimeParameter = trans_datetime != null ?
                new ObjectParameter("trans_datetime", trans_datetime) :
                new ObjectParameter("trans_datetime", typeof(string));
    
            var track_01Parameter = track_01 != null ?
                new ObjectParameter("track_01", track_01) :
                new ObjectParameter("track_01", typeof(string));
    
            var track_02Parameter = track_02 != null ?
                new ObjectParameter("track_02", track_02) :
                new ObjectParameter("track_02", typeof(string));
    
            var track_03Parameter = track_03 != null ?
                new ObjectParameter("track_03", track_03) :
                new ObjectParameter("track_03", typeof(string));
    
            var resultCodeParameter = resultCode != null ?
                new ObjectParameter("resultCode", resultCode) :
                new ObjectParameter("resultCode", typeof(string));
    
            var resultMsgParameter = resultMsg != null ?
                new ObjectParameter("resultMsg", resultMsg) :
                new ObjectParameter("resultMsg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiSaveMagInfo_Result>("sp_ApiSaveMagInfo", wH_IDParameter, staffIdParameter, trans_datetimeParameter, track_01Parameter, track_02Parameter, track_03Parameter, resultCodeParameter, resultMsgParameter);
        }
    
        public virtual ObjectResult<sp_ApiCheckWarehouse_Result> sp_ApiCheckWarehouse(Nullable<int> whid)
        {
            var whidParameter = whid.HasValue ?
                new ObjectParameter("whid", whid) :
                new ObjectParameter("whid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApiCheckWarehouse_Result>("sp_ApiCheckWarehouse", whidParameter);
        }
    
        public virtual ObjectResult<sp_Stock_Result> sp_Stock(Nullable<int> whID, Nullable<int> stID)
        {
            var whIDParameter = whID.HasValue ?
                new ObjectParameter("WhID", whID) :
                new ObjectParameter("WhID", typeof(int));
    
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("StID", stID) :
                new ObjectParameter("StID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Stock_Result>("sp_Stock", whIDParameter, stIDParameter);
        }
    
        public virtual ObjectResult<sp_SearchStock_Result> sp_SearchStock(Nullable<int> whID, Nullable<int> stID, Nullable<int> pdID2, Nullable<int> ctID)
        {
            var whIDParameter = whID.HasValue ?
                new ObjectParameter("WhID", whID) :
                new ObjectParameter("WhID", typeof(int));
    
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("StID", stID) :
                new ObjectParameter("StID", typeof(int));
    
            var pdID2Parameter = pdID2.HasValue ?
                new ObjectParameter("PdID2", pdID2) :
                new ObjectParameter("PdID2", typeof(int));
    
            var ctIDParameter = ctID.HasValue ?
                new ObjectParameter("CtID", ctID) :
                new ObjectParameter("CtID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchStock_Result>("sp_SearchStock", whIDParameter, stIDParameter, pdID2Parameter, ctIDParameter);
        }
    
        public virtual ObjectResult<sp_SearchBorrow_Result> sp_SearchBorrow(string serial, Nullable<System.DateTime> searchFromDate, Nullable<System.DateTime> searchToDate, Nullable<int> searchWare, Nullable<int> searchPro)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(string));
    
            var searchFromDateParameter = searchFromDate.HasValue ?
                new ObjectParameter("searchFromDate", searchFromDate) :
                new ObjectParameter("searchFromDate", typeof(System.DateTime));
    
            var searchToDateParameter = searchToDate.HasValue ?
                new ObjectParameter("searchToDate", searchToDate) :
                new ObjectParameter("searchToDate", typeof(System.DateTime));
    
            var searchWareParameter = searchWare.HasValue ?
                new ObjectParameter("searchWare", searchWare) :
                new ObjectParameter("searchWare", typeof(int));
    
            var searchProParameter = searchPro.HasValue ?
                new ObjectParameter("searchPro", searchPro) :
                new ObjectParameter("searchPro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchBorrow_Result>("sp_SearchBorrow", serialParameter, searchFromDateParameter, searchToDateParameter, searchWareParameter, searchProParameter);
        }
    
        public virtual ObjectResult<sp_SearchDocument_Result> sp_SearchDocument(string serial, Nullable<System.DateTime> searchFromDate, Nullable<System.DateTime> searchToDate, Nullable<int> searchWare, Nullable<int> searchPro, Nullable<int> doctype, Nullable<int> status, Nullable<int> stidpermit)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(string));
    
            var searchFromDateParameter = searchFromDate.HasValue ?
                new ObjectParameter("searchFromDate", searchFromDate) :
                new ObjectParameter("searchFromDate", typeof(System.DateTime));
    
            var searchToDateParameter = searchToDate.HasValue ?
                new ObjectParameter("searchToDate", searchToDate) :
                new ObjectParameter("searchToDate", typeof(System.DateTime));
    
            var searchWareParameter = searchWare.HasValue ?
                new ObjectParameter("searchWare", searchWare) :
                new ObjectParameter("searchWare", typeof(int));
    
            var searchProParameter = searchPro.HasValue ?
                new ObjectParameter("searchPro", searchPro) :
                new ObjectParameter("searchPro", typeof(int));
    
            var doctypeParameter = doctype.HasValue ?
                new ObjectParameter("doctype", doctype) :
                new ObjectParameter("doctype", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var stidpermitParameter = stidpermit.HasValue ?
                new ObjectParameter("stidpermit", stidpermit) :
                new ObjectParameter("stidpermit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchDocument_Result>("sp_SearchDocument", serialParameter, searchFromDateParameter, searchToDateParameter, searchWareParameter, searchProParameter, doctypeParameter, statusParameter, stidpermitParameter);
        }
    
        public virtual ObjectResult<sp_DocumentList_Result> sp_DocumentList(Nullable<int> whid, string doctype)
        {
            var whidParameter = whid.HasValue ?
                new ObjectParameter("whid", whid) :
                new ObjectParameter("whid", typeof(int));
    
            var doctypeParameter = doctype != null ?
                new ObjectParameter("doctype", doctype) :
                new ObjectParameter("doctype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DocumentList_Result>("sp_DocumentList", whidParameter, doctypeParameter);
        }
    
        public virtual ObjectResult<sp_CheckSerialINReceive_Result> sp_CheckSerialINReceive(Nullable<int> docID)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("docID", docID) :
                new ObjectParameter("docID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CheckSerialINReceive_Result>("sp_CheckSerialINReceive", docIDParameter);
        }
    
        public virtual ObjectResult<sp_WarehouseIndex_Result> sp_WarehouseIndex(Nullable<int> stID)
        {
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("StID", stID) :
                new ObjectParameter("StID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WarehouseIndex_Result>("sp_WarehouseIndex", stIDParameter);
        }
    
        public virtual ObjectResult<sp_WarehouseSearch_Result> sp_WarehouseSearch(Nullable<int> stID, string name)
        {
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("StID", stID) :
                new ObjectParameter("StID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WarehouseSearch_Result>("sp_WarehouseSearch", stIDParameter, nameParameter);
        }
    
        public virtual ObjectResult<sp_WorkStationIndex_Result> sp_WorkStationIndex(Nullable<int> stid)
        {
            var stidParameter = stid.HasValue ?
                new ObjectParameter("stid", stid) :
                new ObjectParameter("stid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WorkStationIndex_Result>("sp_WorkStationIndex", stidParameter);
        }
    
        public virtual ObjectResult<sp_WorkStationSearch_Result> sp_WorkStationSearch(Nullable<int> stid, Nullable<int> searchWare)
        {
            var stidParameter = stid.HasValue ?
                new ObjectParameter("stid", stid) :
                new ObjectParameter("stid", typeof(int));
    
            var searchWareParameter = searchWare.HasValue ?
                new ObjectParameter("searchWare", searchWare) :
                new ObjectParameter("searchWare", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WorkStationSearch_Result>("sp_WorkStationSearch", stidParameter, searchWareParameter);
        }
    
        public virtual ObjectResult<sp_GetMainWarehouse_Result> sp_GetMainWarehouse(Nullable<int> stID)
        {
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("stID", stID) :
                new ObjectParameter("stID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetMainWarehouse_Result>("sp_GetMainWarehouse", stIDParameter);
        }
    
        public virtual ObjectResult<sp_WarehouseTransferAuthority_Result> sp_WarehouseTransferAuthority(Nullable<int> stID)
        {
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("stID", stID) :
                new ObjectParameter("stID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WarehouseTransferAuthority_Result>("sp_WarehouseTransferAuthority", stIDParameter);
        }
    
        public virtual ObjectResult<sp_WarehouseAuthority_Result> sp_WarehouseAuthority(Nullable<int> stID)
        {
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("stID", stID) :
                new ObjectParameter("stID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WarehouseAuthority_Result>("sp_WarehouseAuthority", stIDParameter);
        }
    
        public virtual ObjectResult<sp_SearchCard_Result> sp_SearchCard(string serialBegin, string serialEnd, Nullable<System.DateTime> beginDate, Nullable<System.DateTime> endDate)
        {
            var serialBeginParameter = serialBegin != null ?
                new ObjectParameter("serialBegin", serialBegin) :
                new ObjectParameter("serialBegin", typeof(string));
    
            var serialEndParameter = serialEnd != null ?
                new ObjectParameter("serialEnd", serialEnd) :
                new ObjectParameter("serialEnd", typeof(string));
    
            var beginDateParameter = beginDate.HasValue ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchCard_Result>("sp_SearchCard", serialBeginParameter, serialEndParameter, beginDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<sp_SaveCardManual_Result> sp_SaveCardManual(string addrNo, string ampDesc, string ampDescEng, string birthDateStr, string birthFlag, string distDesc, string distDescEng, string docNo, string docType, string reqMasRef, string expDateStr, string fname, string fnameEng, string issDateStr, string issOffLocCode, string lane, string lname, string lnameEng, string locFullDesc, string message, string natDesc, string offLocDesc, string offLocEngDesc, string offRegDesc, string offRegEngDesc, string pcNo, string pltCode, string pltDesc, string pltEngDesc, string pltNo, string pltPrnDesc, string prevExpDateStr, string prevIssDateStr, string prevOffLocDesc, string prevOffRegDesc, string prevOffRegEngDesc, string prevPltDesc, string prevPltNo, string prvCode, string prvDesc, string prvDescEng, string rcpNo, string reqDateStr, string reqNo, string reqTrDesc, string sex, string soi, string street, string titleAbrev, string titleDesc, string titleEngAbrev, string villageNo, string zipCode, string alienFlag, string ccFlag, string dCICode, string conditionDesc, string organDonateFlag, string tRSFlag, string firstIssueDateStr, string pltDescShort, string pltNo1, string pltNo2, string prevPltDescShort, string prevPltNo1, string prevPltNo2, string pltNoEng, string wH_ID, string staffId, string workstationId, string productType, string cardEIN, string qrCode, Nullable<System.DateTime> docDate, string remark)
        {
            var addrNoParameter = addrNo != null ?
                new ObjectParameter("addrNo", addrNo) :
                new ObjectParameter("addrNo", typeof(string));
    
            var ampDescParameter = ampDesc != null ?
                new ObjectParameter("ampDesc", ampDesc) :
                new ObjectParameter("ampDesc", typeof(string));
    
            var ampDescEngParameter = ampDescEng != null ?
                new ObjectParameter("ampDescEng", ampDescEng) :
                new ObjectParameter("ampDescEng", typeof(string));
    
            var birthDateStrParameter = birthDateStr != null ?
                new ObjectParameter("birthDateStr", birthDateStr) :
                new ObjectParameter("birthDateStr", typeof(string));
    
            var birthFlagParameter = birthFlag != null ?
                new ObjectParameter("birthFlag", birthFlag) :
                new ObjectParameter("birthFlag", typeof(string));
    
            var distDescParameter = distDesc != null ?
                new ObjectParameter("distDesc", distDesc) :
                new ObjectParameter("distDesc", typeof(string));
    
            var distDescEngParameter = distDescEng != null ?
                new ObjectParameter("distDescEng", distDescEng) :
                new ObjectParameter("distDescEng", typeof(string));
    
            var docNoParameter = docNo != null ?
                new ObjectParameter("docNo", docNo) :
                new ObjectParameter("docNo", typeof(string));
    
            var docTypeParameter = docType != null ?
                new ObjectParameter("docType", docType) :
                new ObjectParameter("docType", typeof(string));
    
            var reqMasRefParameter = reqMasRef != null ?
                new ObjectParameter("reqMasRef", reqMasRef) :
                new ObjectParameter("reqMasRef", typeof(string));
    
            var expDateStrParameter = expDateStr != null ?
                new ObjectParameter("expDateStr", expDateStr) :
                new ObjectParameter("expDateStr", typeof(string));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var fnameEngParameter = fnameEng != null ?
                new ObjectParameter("fnameEng", fnameEng) :
                new ObjectParameter("fnameEng", typeof(string));
    
            var issDateStrParameter = issDateStr != null ?
                new ObjectParameter("issDateStr", issDateStr) :
                new ObjectParameter("issDateStr", typeof(string));
    
            var issOffLocCodeParameter = issOffLocCode != null ?
                new ObjectParameter("issOffLocCode", issOffLocCode) :
                new ObjectParameter("issOffLocCode", typeof(string));
    
            var laneParameter = lane != null ?
                new ObjectParameter("lane", lane) :
                new ObjectParameter("lane", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var lnameEngParameter = lnameEng != null ?
                new ObjectParameter("lnameEng", lnameEng) :
                new ObjectParameter("lnameEng", typeof(string));
    
            var locFullDescParameter = locFullDesc != null ?
                new ObjectParameter("locFullDesc", locFullDesc) :
                new ObjectParameter("locFullDesc", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            var natDescParameter = natDesc != null ?
                new ObjectParameter("natDesc", natDesc) :
                new ObjectParameter("natDesc", typeof(string));
    
            var offLocDescParameter = offLocDesc != null ?
                new ObjectParameter("offLocDesc", offLocDesc) :
                new ObjectParameter("offLocDesc", typeof(string));
    
            var offLocEngDescParameter = offLocEngDesc != null ?
                new ObjectParameter("offLocEngDesc", offLocEngDesc) :
                new ObjectParameter("offLocEngDesc", typeof(string));
    
            var offRegDescParameter = offRegDesc != null ?
                new ObjectParameter("offRegDesc", offRegDesc) :
                new ObjectParameter("offRegDesc", typeof(string));
    
            var offRegEngDescParameter = offRegEngDesc != null ?
                new ObjectParameter("offRegEngDesc", offRegEngDesc) :
                new ObjectParameter("offRegEngDesc", typeof(string));
    
            var pcNoParameter = pcNo != null ?
                new ObjectParameter("pcNo", pcNo) :
                new ObjectParameter("pcNo", typeof(string));
    
            var pltCodeParameter = pltCode != null ?
                new ObjectParameter("pltCode", pltCode) :
                new ObjectParameter("pltCode", typeof(string));
    
            var pltDescParameter = pltDesc != null ?
                new ObjectParameter("pltDesc", pltDesc) :
                new ObjectParameter("pltDesc", typeof(string));
    
            var pltEngDescParameter = pltEngDesc != null ?
                new ObjectParameter("pltEngDesc", pltEngDesc) :
                new ObjectParameter("pltEngDesc", typeof(string));
    
            var pltNoParameter = pltNo != null ?
                new ObjectParameter("pltNo", pltNo) :
                new ObjectParameter("pltNo", typeof(string));
    
            var pltPrnDescParameter = pltPrnDesc != null ?
                new ObjectParameter("pltPrnDesc", pltPrnDesc) :
                new ObjectParameter("pltPrnDesc", typeof(string));
    
            var prevExpDateStrParameter = prevExpDateStr != null ?
                new ObjectParameter("prevExpDateStr", prevExpDateStr) :
                new ObjectParameter("prevExpDateStr", typeof(string));
    
            var prevIssDateStrParameter = prevIssDateStr != null ?
                new ObjectParameter("prevIssDateStr", prevIssDateStr) :
                new ObjectParameter("prevIssDateStr", typeof(string));
    
            var prevOffLocDescParameter = prevOffLocDesc != null ?
                new ObjectParameter("prevOffLocDesc", prevOffLocDesc) :
                new ObjectParameter("prevOffLocDesc", typeof(string));
    
            var prevOffRegDescParameter = prevOffRegDesc != null ?
                new ObjectParameter("prevOffRegDesc", prevOffRegDesc) :
                new ObjectParameter("prevOffRegDesc", typeof(string));
    
            var prevOffRegEngDescParameter = prevOffRegEngDesc != null ?
                new ObjectParameter("prevOffRegEngDesc", prevOffRegEngDesc) :
                new ObjectParameter("prevOffRegEngDesc", typeof(string));
    
            var prevPltDescParameter = prevPltDesc != null ?
                new ObjectParameter("prevPltDesc", prevPltDesc) :
                new ObjectParameter("prevPltDesc", typeof(string));
    
            var prevPltNoParameter = prevPltNo != null ?
                new ObjectParameter("prevPltNo", prevPltNo) :
                new ObjectParameter("prevPltNo", typeof(string));
    
            var prvCodeParameter = prvCode != null ?
                new ObjectParameter("prvCode", prvCode) :
                new ObjectParameter("prvCode", typeof(string));
    
            var prvDescParameter = prvDesc != null ?
                new ObjectParameter("prvDesc", prvDesc) :
                new ObjectParameter("prvDesc", typeof(string));
    
            var prvDescEngParameter = prvDescEng != null ?
                new ObjectParameter("prvDescEng", prvDescEng) :
                new ObjectParameter("prvDescEng", typeof(string));
    
            var rcpNoParameter = rcpNo != null ?
                new ObjectParameter("rcpNo", rcpNo) :
                new ObjectParameter("rcpNo", typeof(string));
    
            var reqDateStrParameter = reqDateStr != null ?
                new ObjectParameter("reqDateStr", reqDateStr) :
                new ObjectParameter("reqDateStr", typeof(string));
    
            var reqNoParameter = reqNo != null ?
                new ObjectParameter("reqNo", reqNo) :
                new ObjectParameter("reqNo", typeof(string));
    
            var reqTrDescParameter = reqTrDesc != null ?
                new ObjectParameter("reqTrDesc", reqTrDesc) :
                new ObjectParameter("reqTrDesc", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var soiParameter = soi != null ?
                new ObjectParameter("soi", soi) :
                new ObjectParameter("soi", typeof(string));
    
            var streetParameter = street != null ?
                new ObjectParameter("street", street) :
                new ObjectParameter("street", typeof(string));
    
            var titleAbrevParameter = titleAbrev != null ?
                new ObjectParameter("titleAbrev", titleAbrev) :
                new ObjectParameter("titleAbrev", typeof(string));
    
            var titleDescParameter = titleDesc != null ?
                new ObjectParameter("titleDesc", titleDesc) :
                new ObjectParameter("titleDesc", typeof(string));
    
            var titleEngAbrevParameter = titleEngAbrev != null ?
                new ObjectParameter("titleEngAbrev", titleEngAbrev) :
                new ObjectParameter("titleEngAbrev", typeof(string));
    
            var villageNoParameter = villageNo != null ?
                new ObjectParameter("villageNo", villageNo) :
                new ObjectParameter("villageNo", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("zipCode", zipCode) :
                new ObjectParameter("zipCode", typeof(string));
    
            var alienFlagParameter = alienFlag != null ?
                new ObjectParameter("alienFlag", alienFlag) :
                new ObjectParameter("alienFlag", typeof(string));
    
            var ccFlagParameter = ccFlag != null ?
                new ObjectParameter("ccFlag", ccFlag) :
                new ObjectParameter("ccFlag", typeof(string));
    
            var dCICodeParameter = dCICode != null ?
                new ObjectParameter("DCICode", dCICode) :
                new ObjectParameter("DCICode", typeof(string));
    
            var conditionDescParameter = conditionDesc != null ?
                new ObjectParameter("conditionDesc", conditionDesc) :
                new ObjectParameter("conditionDesc", typeof(string));
    
            var organDonateFlagParameter = organDonateFlag != null ?
                new ObjectParameter("organDonateFlag", organDonateFlag) :
                new ObjectParameter("organDonateFlag", typeof(string));
    
            var tRSFlagParameter = tRSFlag != null ?
                new ObjectParameter("TRSFlag", tRSFlag) :
                new ObjectParameter("TRSFlag", typeof(string));
    
            var firstIssueDateStrParameter = firstIssueDateStr != null ?
                new ObjectParameter("firstIssueDateStr", firstIssueDateStr) :
                new ObjectParameter("firstIssueDateStr", typeof(string));
    
            var pltDescShortParameter = pltDescShort != null ?
                new ObjectParameter("pltDescShort", pltDescShort) :
                new ObjectParameter("pltDescShort", typeof(string));
    
            var pltNo1Parameter = pltNo1 != null ?
                new ObjectParameter("pltNo1", pltNo1) :
                new ObjectParameter("pltNo1", typeof(string));
    
            var pltNo2Parameter = pltNo2 != null ?
                new ObjectParameter("pltNo2", pltNo2) :
                new ObjectParameter("pltNo2", typeof(string));
    
            var prevPltDescShortParameter = prevPltDescShort != null ?
                new ObjectParameter("prevPltDescShort", prevPltDescShort) :
                new ObjectParameter("prevPltDescShort", typeof(string));
    
            var prevPltNo1Parameter = prevPltNo1 != null ?
                new ObjectParameter("prevPltNo1", prevPltNo1) :
                new ObjectParameter("prevPltNo1", typeof(string));
    
            var prevPltNo2Parameter = prevPltNo2 != null ?
                new ObjectParameter("prevPltNo2", prevPltNo2) :
                new ObjectParameter("prevPltNo2", typeof(string));
    
            var pltNoEngParameter = pltNoEng != null ?
                new ObjectParameter("pltNoEng", pltNoEng) :
                new ObjectParameter("pltNoEng", typeof(string));
    
            var wH_IDParameter = wH_ID != null ?
                new ObjectParameter("WH_ID", wH_ID) :
                new ObjectParameter("WH_ID", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            var workstationIdParameter = workstationId != null ?
                new ObjectParameter("workstationId", workstationId) :
                new ObjectParameter("workstationId", typeof(string));
    
            var productTypeParameter = productType != null ?
                new ObjectParameter("productType", productType) :
                new ObjectParameter("productType", typeof(string));
    
            var cardEINParameter = cardEIN != null ?
                new ObjectParameter("CardEIN", cardEIN) :
                new ObjectParameter("CardEIN", typeof(string));
    
            var qrCodeParameter = qrCode != null ?
                new ObjectParameter("qrCode", qrCode) :
                new ObjectParameter("qrCode", typeof(string));
    
            var docDateParameter = docDate.HasValue ?
                new ObjectParameter("DocDate", docDate) :
                new ObjectParameter("DocDate", typeof(System.DateTime));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("Remark", remark) :
                new ObjectParameter("Remark", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SaveCardManual_Result>("sp_SaveCardManual", addrNoParameter, ampDescParameter, ampDescEngParameter, birthDateStrParameter, birthFlagParameter, distDescParameter, distDescEngParameter, docNoParameter, docTypeParameter, reqMasRefParameter, expDateStrParameter, fnameParameter, fnameEngParameter, issDateStrParameter, issOffLocCodeParameter, laneParameter, lnameParameter, lnameEngParameter, locFullDescParameter, messageParameter, natDescParameter, offLocDescParameter, offLocEngDescParameter, offRegDescParameter, offRegEngDescParameter, pcNoParameter, pltCodeParameter, pltDescParameter, pltEngDescParameter, pltNoParameter, pltPrnDescParameter, prevExpDateStrParameter, prevIssDateStrParameter, prevOffLocDescParameter, prevOffRegDescParameter, prevOffRegEngDescParameter, prevPltDescParameter, prevPltNoParameter, prvCodeParameter, prvDescParameter, prvDescEngParameter, rcpNoParameter, reqDateStrParameter, reqNoParameter, reqTrDescParameter, sexParameter, soiParameter, streetParameter, titleAbrevParameter, titleDescParameter, titleEngAbrevParameter, villageNoParameter, zipCodeParameter, alienFlagParameter, ccFlagParameter, dCICodeParameter, conditionDescParameter, organDonateFlagParameter, tRSFlagParameter, firstIssueDateStrParameter, pltDescShortParameter, pltNo1Parameter, pltNo2Parameter, prevPltDescShortParameter, prevPltNo1Parameter, prevPltNo2Parameter, pltNoEngParameter, wH_IDParameter, staffIdParameter, workstationIdParameter, productTypeParameter, cardEINParameter, qrCodeParameter, docDateParameter, remarkParameter);
        }
    }
}
