//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int UgID { get; set; }
        public string MdCode { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual UserGroup UserGroup { get; set; }

        public int UserGroupID { get; set; }
        public string UserGroupName { get; set; }


        public List<ModuleList> Menu { get; set; }

    }

    public class ModuleList
    {
        public string ModuleName { get; set; }
        public string ModuleParent { get; set; }
    }
}
