//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DocumentDetails = new HashSet<DocumentDetail>();
            this.Stocks = new HashSet<Stock>();
            this.WarehouseMinimums = new HashSet<WarehouseMinimum>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "กรุณากรอกรหัสวัสดุ")]
        public string Code { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกกลุ่มวัสดุ")]
        public Nullable<int> CtID { get; set; }
        [Required(ErrorMessage = "กรุณากรอกชื่อวัสดุ")]
        public string Name { get; set; }
        //[Required(ErrorMessage = "กรุณากรอกจำนวนขั้นต่ำ")]
        //[RegularExpression("([0-9]+)" , ErrorMessage = "กรุณากรอกจำนวนขั้นต่ำ")]
        public Nullable<int> MinStock { get; set; }
        public string SerialControl { get; set; }
        public string IsAsset { get; set; }
    
        public string CategoryName { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseMinimum> WarehouseMinimums { get; set; }
    }
}
