//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialImagePart
    {
        public int ID { get; set; }
        public string SerialNo { get; set; }
        public string ImageSize { get; set; }
        public string PartSize { get; set; }
        public string PartPosition { get; set; }
        public string PartData { get; set; }
    }
}
