//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffWarehouse
    {
        public int StID { get; set; }
        public int WhID { get; set; }
        public string IsManager { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
