//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Documents = new HashSet<Document>();
            this.StaffWarehouses = new HashSet<StaffWarehouse>();
            this.TransferStaffs = new HashSet<TransferStaff>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "กรุณากรอกชื่อเจ้าหน้าที่")]
        public string Name { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "กรุณากรอก Username")]
        public string UserLogin { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "กรุณากรอก Password")]
        public string UserPassword { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกกลุ่มผู้ใช้")]
        public Nullable<int> UgID { get; set; }
        public string TelNo { get; set; }
        public string Email { get; set; }
        public string AuthorizeNameTH { get; set; }
        public string AuthorizeNameEN { get; set; }
        public string AuthorizeLastNameTH { get; set; }
        public string AuthorizeLastNameEN { get; set; }
        public string Signature { get; set; }
        public string TitleTH { get; set; }
        public string TitleEN { get; set; }
        
        public string WhName { get; set; }
        [DataType(DataType.Password)]
        public string NewUserPassword { get; set; }

        public string LoginErrorMessage { get; set; }
		public List<StaffWarehouseList> StWh { get; set; }
        //[Required(ErrorMessage = "กรุณาเลือกสิทธิการออกใบอนุญาต")]
        public Nullable<int> AuthorityType { get; set; }
        public Nullable<int> RefAuthorize { get; set; }
        public string IdCard { get; set; }
        public string AuthorizeIdCard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffWarehouse> StaffWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferStaff> TransferStaffs { get; set; }
    }
    public class StaffWarehouseList
    {
        public int StID { get; set; }
        public int WhID { get; set; }
        public string IsManager { get; set; }
        public string WhName { get; set; }
    }

}
