//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHistory
    {
        public int IsID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> StID { get; set; }
        public string Status { get; set; }
    
        public virtual Issue Issue { get; set; }
    }
}
